# Change these first
owner: thomas-iniguez-visioli # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository
assignees:
  - alphaleadership
sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: discord
    url: https://discord.com
  - name: twitter
    url: https://x.com
    expectedStatusCodes:
        - 400
  - name: instagram
    url: https://instagram.com
  - name: twitch
    url: https://twitch.tv
  - name: github
    url: https://github.com
  - name: stack
    url: https://stackoverflow.com
  - name: toutatice
    url: https://www.toutatice.fr
  - name: linkedin
    url: https://www.linkedin.com 
i18n:
  activeIncidents: Incidents en cours
  allSystemsOperational: Tous les systèmes fonctionnent
  activeIncidentSummary: Ouvert le $DATE et a $POSTS publications
  averageResponseTime: "Temps de réponse moyen : $TIME ms"
  duration: Durée
  durationMin: $DURATION minutes
  duration1Y: 1 an
  durationAll: tout
  errorHome: Retour à la page d'accueil
  errorTitle: Une erreur est survenue
  errorText: Vous pouvez réessayer dans un moment.
  history: Historique
  incidentCompleted: Terminé
  incidentReport: "Rapport d'incident n° $NUMBER →"
  incidentFixed: Résolu
  incidentOngoing: En cours
  incidentScheduled: Prévu
  incidentOpenedAt: Ouvert à
  incidentClosedAt: Fermé à
  incidentViewOnGitHub: Voir et suivre sur GitHub
  liveStatus: Statut en direct
  overallUptimeTitle: Disponibilité totale
  overallUptime: "Disponibilité totale : $UPTIME"
  pastScheduledMaintenance: Maintenance planifiée précédente
  startedAt: Commencé à
  startsAt: Commence à
  scheduledMaintenance: Maintenance planifiée
  scheduledMaintenanceSummaryStarted: Commencé le $DATE pendant $DURATION minutes
  scheduledMaintenanceSummaryStarts: Commence le $DATE dans $DURATION minutes
  responseTime: Temps de réponse
  responseTimeMs: Temps de réponse (ms)
  uptime: Disponibilité
  up: En ligne
  down: Hors ligne
  degraded: Dégradé
  loading: Chargement
  footer: "Cette page est [open source]($REPO) et fonctionne avec [Upptime](https://upptime.js.org)."
  locale: fr-FR

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
   
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
