name: Delete Issues with Status Tag

on:
  workflow_dispatch: # Permet d'exécuter le workflow manuellement

jobs:
  delete_issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete issues with "status" tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Utilise le token d'accès personnel de GitHub
        run: |
          # Récupérer toutes les issues
          issues=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/issues?state=open")

          # Supprimer les issues avec le tag "status"
          echo "$issues" | jq -c '.[]' | while IFS= read -r issue; do
            issue_number=$(echo "$issue" | jq -r '.number')
            labels=$(echo "$issue" | jq -r '.labels | map(.name)')

            if echo "$labels" | grep -q "status"; then
              echo "Deleting issue #$issue_number"
              curl -s -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
                "https://api.github.com/repos/${{ github.repository }}/issues/$issue_number"
            fi
          done
